### PR TITLE
Fix non-existent directory errors in mnist example

### LINKED ISSUE #143: mnist example: non-existent user directories causes "no such file or directory" errors
The directories for data, models and logs specified in user's run config file must exist before running the task, else "no such file or directory" errors might be triggered.

### PR DESCRIPTION
**Pull request by xyhuang**
Auto create data, model, and log directories if they do not exist.

Fixes #143

### CODE REVIEW

**Comment by sergey-serebryakov** [comment]
Looks good. @xyhuang, what was the use case that triggered this fix? I thought the PR long time that introduced [this](https://github.com/mlperf/mlbox/blob/master/runners/mlcommons_box_docker/mlcommons_box_docker/docker_run.py#L84) and [this](https://github.com/mlperf/mlbox/blob/master/runners/mlcommons_box_docker/mlcommons_box_docker/docker_run.py#L92) lines fixed the non-existing directory issue.
Is this for K8S runner?

**Comment by xyhuang** [comment]
@sergey-serebryakov yeah i think k8s runner is not able to create the directories inside a k8s volume

**Comment by sergey-serebryakov** [comment]
@xyhuang So, we just removed the `examples` folder. I'll move this PR to `https://github.com/mlperf/mlcube_examples/mnist` that needs to be re-designed a bit - it does not contain the source and is supposed to pull docker image from docker hub.

**Comment by xyhuang** [comment]
ok i will close this for now.

**Pull request closed without merging**
